name: Flutter Windows Build

on:
  push:
    branches:
      - main  # 根据需要修改为你的默认分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 使用Windows环境

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Application
        run: flutter build windows --release

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3  # 更新为v3
        with:
          name: windows-build
          path: build\windows\runner\Release\*.exe  # 上传构建的可执行文件
